### ISSUE TITLE
Firefox leaves gaps when tiling.

### ISSUE THREAD

**Issue by HACKER097** [blrsn/zentile#37]
I have gaps set to zero, but Firefox still has gaps, or rather a border around it. This seems to only be an issue with Firefox and its forks, Brave tiles perfectly. I am on Xubuntu 20.04 using Xfce 4.14. I have included a screenshot of the behaviour.

https://i.imgur.com/ST4nhOm.png

**Comment by leukipp** [comment]
You can try to disable **Client-Side Decorations**. (Related: https://github.com/leukipp/cortile/issues/3#issuecomment-1121535591)

**Comment by HACKER097** [comment]
Thank you, that fixed it
